language: node_js
node_js:
- '8'
jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    
    before_script:
      - npm run lint

deploy:
  provider: npm
  email: kumar.limbu@me.com
  api_key:
    secure: $NPM_API_KEY
  on:
    tags: true
    repo: limbuster/generator-koajs
