version: ~> 1.0
language: node_js
node_js:
- '12.13'
jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    
    before_script:
      - npm run lint

deploy:
  provider: npm
  email: kumar.limbu@me.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    repo: limbuster/generator-koajs
